### PR TITLE
Fix Vike + styled-components + Grommet integration

### PR DESCRIPTION
**Pull request by lourot**
This now correctly leads to

    $ pnpm run prod
    Server running at http://localhost:3000
    Found styles:  <style data-styled="true" data-styled-version="5.3.9">.hBYmVK{width:100%;background-color:red;}/*!sc*/
    data-styled.g1[id="sc-beqWaB"]{content:"hBYmVK,"}/*!sc*/
    </style>

### CODE REVIEW

**Comment by tdonhauser** [comment]
Thanks for your help! Unfortunately this doesn't solve my problem. When I load the page it finds some styles but, the page is not painted correctly. This ist my First Contentful Paint with your fix included:

image

As you can see the background colors are still missing. Once the page is loaded it looks like this:

image

Shouldn't `sheet.getStyleTags()` collect the background colors of styled components as well?

**Comment by lourot** [comment]
I just wanted to unblock you on the issue you mentioned, but there may still be other issues in the way you are integrating Vike, styled-component and Grommet. Did you dig a bit?

**Comment by tdonhauser** [comment]
I'm trying to solve this since a couple of weeks now and not getting any further. Searched all issues and threads on grommet, vike and stackoverflow for a solution without success. You said it could be related to the way I'm using Vike, styled-components and Grommet. What am I doing wrong?

**Comment by lourot** [comment]
styled-components and grommet are new to me but I'll have another look tomorrow

**Comment by tdonhauser** [comment]
@AurelienLourot thanks a lot!

**Comment by lourot** [comment]
The only place we use styled-components in this repo is

```
// /pages/index/index.page.tsx
const Container = styled.div`
  width: 100%;
  background-color: red;
`;
```

and this is being picked up by `sheet.getStyleTags()` as we can see in the server log:

```
$ pnpm run prod
Server running at http://localhost:3000
Found styles:  <style data-styled="true" data-styled-version="5.3.9">.hBYmVK{width:100%;background-color:red;}/*!sc*/
data-styled.g1[id="sc-beqWaB"]{content:"hBYmVK,"}/*!sc*/
</style>
```

So up to that point (call to `sheet.getStyleTags()`) everything is as expected. However it's true that the HTML delivered by the server to the client doesn't have a red background. Digging

**Comment by lourot** [comment]
Fixed. You were outputting `<style><style>...</style></style>` instead of `<style>...</style>` in the server's HTML

**Comment by tdonhauser** [comment]
Yes. And the grommet components 

```
      <Grommet
        theme={{
          global: {
            colors: { doc: "#ff99cc" },
          },
        }}
      >        
        <Box pad="large" background="doc">
          <Text color="red">Debugtext</Text>
        </Box>
      </Grommet>,
```

have styles as well (see pink background for example). These are not collected, right?

**Comment by lourot** [comment]
> These are not collected, right?

Yes because this is not styled-components syntax, i.e. this is not the
```
styled.something`...`
```
syntax, so `sheet.getStyleTags()` won't pick it up if I understand correctly.

**Comment by tdonhauser** [comment]
> Fixed. You were outputting `<style><style>...</style></style>` instead of `<style>...</style>` in the server's HTML

Yes! Wow, didn't see that. That solves the problem for these styles:
```
// /pages/index/index.page.tsx
const Container = styled.div`
  width: 100%;
  background-color: red;
`;
```

Thanks! Now I just need to know why the styles from grommet components are not found.

**Comment by tdonhauser** [comment]
> Yes because this is not styled-components syntax, i.e. this is not the

Ahh ok. Any idea how to collect these as well and inject them into the html?

**Comment by lourot** [comment]
Not off the top of my head, I'd have to read Grommet's docs. It's new to me

**Pull request merged**
